// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using books.context;

#nullable disable

namespace books.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20260305091408_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("books.models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Ursula K.",
                            LastName = "Le Guin"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Neil",
                            LastName = "Gaiman"
                        },
                        new
                        {
                            ID = 3,
                            FirstName = "Brandon",
                            LastName = "Sanderson"
                        },
                        new
                        {
                            ID = 4,
                            FirstName = "Tana",
                            LastName = "French"
                        },
                        new
                        {
                            ID = 5,
                            FirstName = "Ted",
                            LastName = "Chiang"
                        },
                        new
                        {
                            ID = 6,
                            FirstName = "Maggie",
                            LastName = "O'Farrell"
                        },
                        new
                        {
                            ID = 7,
                            FirstName = "Andy",
                            LastName = "Weir"
                        },
                        new
                        {
                            ID = 8,
                            FirstName = "Shirley",
                            LastName = "Jackson"
                        });
                });

            modelBuilder.Entity("books.models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryId = 1,
                            Title = "The Left Hand of Darkness"
                        },
                        new
                        {
                            ID = 2,
                            CategoryId = 2,
                            Title = "Neverwhere"
                        },
                        new
                        {
                            ID = 3,
                            CategoryId = 2,
                            Title = "The Way of Kings"
                        },
                        new
                        {
                            ID = 4,
                            CategoryId = 1,
                            Title = "The Martian"
                        },
                        new
                        {
                            ID = 5,
                            CategoryId = 1,
                            Title = "Exhalation"
                        },
                        new
                        {
                            ID = 6,
                            CategoryId = 3,
                            Title = "The Likeness"
                        },
                        new
                        {
                            ID = 7,
                            CategoryId = 8,
                            Title = "The Haunting of Hill House"
                        },
                        new
                        {
                            ID = 8,
                            CategoryId = 5,
                            Title = "Hamnet"
                        });
                });

            modelBuilder.Entity("books.models.BookAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookAuthor");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BookId = 1
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 2
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 3
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 4
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 5
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 6
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 7
                        },
                        new
                        {
                            AuthorId = 6,
                            BookId = 8
                        });
                });

            modelBuilder.Entity("books.models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Mystery / Thriller"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Literary Fiction"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Young Adult"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("books.models.Book", b =>
                {
                    b.HasOne("books.models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("books.models.BookAuthor", b =>
                {
                    b.HasOne("books.models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("books.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("books.models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
